### ISSUE TITLE
Create reusable components for small pieces of app functionality

### ISSUE THREAD

**Issue by blickly** [aimpowered/ZoomCompanion#30]
Right now, most of the app functionality is directly implemented in large files that cover disparate functions, like app/main/page.tsx, or app/main/NameTag.tsx

It would be preferable to abstract out reusable components of functionality into components (e.g. such as one for selecting a waving hand) and refactor the existing code to use those.

**Comment by Shaomei** [comment]
[https://github.com/aimpowered/ZoomCompanion/pull/57](url)

**Comment by Shaomei** [comment]
FYI @BrennanJones @kexinF I just landed the refactored NameTagForm component. I will work on refactoring the handwave component next, hoping to submit the change by the end of Friday.
