### ISSUE TITLE
"Display Name Tag" setting inconsistent after logging out

### ISSUE THREAD

**Issue by blickly** [aimpowered/ZoomCompanion#69]
When you log out with the "Display Name Tag" checkbox selected, and then log back in again, the checkbox is populated as being selected, but the video has the nametag not displayed.  This is inconsistent.

We should update the nametag element and video to start in a consistent state.

**Comment by Shaomei** [comment]
@BrennanJones, just to confirmed this issue is fixed and can be closed?
