### ISSUE TITLE
[Nametag] Remove "Full Name" field in the nametag

### ISSUE THREAD

**Issue by Shaomei** [aimpowered/ZoomCompanion#76]
"Full Name" is redundant with "Preferred Name", should be removed from the nametag form.

Remember to also update the type definition for nametag and the DB save/read.

**Comment by Shaomei** [comment]
Hi @kexinF, @aditi-1402 is taking this up as her starter task, can you support her? E.g. answer her questions and point her to the right place?

**Comment by kexinF** [comment]
For sure! Please let me know if you need anything from my side or need to schedule a meeting @aditi-1402 . Thank you very much!

**Comment by aditi-1402** [comment]
@kexinF Thank you! Sure

**Comment by aditi-1402** [comment]
#84

**Comment by Shaomei** [comment]
This is fixed by PR #87.

Close the issue now.
