### ISSUE TITLE
[UI] Make "name tag" tab the default landing page instead of "Mindfulness"

### ISSUE THREAD

**Issue by Shaomei** [aimpowered/ZoomCompanion#78]
Currently the "Mindfulness" tab is shown as default after logging in (see screenshot below). We should change it so that the "Name Tag" tab is the default.

<img width="545" alt="Screenshot 2024-06-15 at 7 39 34 PM" src="https://github.com/aimpowered/ZoomCompanion/assets/202047/3282f1b1-da25-422e-963f-c95512a3067b">

**Comment by Shaomei** [comment]
@kexinF do you know why the second tab is shown as the landing page by default?

**Comment by kexinF** [comment]
In main/tabs.tsx line 27, activeTab is set to be index 1 by default:
activeTab: (props.children as TabElement[])[1].props['page-label']

**Comment by ssunil3232** [comment]
@Shaomei @kexinF Hi Is there already being worked on or can i fix this issue.

**Comment by Shaomei** [comment]
@ssunil3232 thanks for checking. It is actually fixed. I should have closed the issue last week.
