### ISSUE TITLE
[UI] gray out the carousal left and right arrow at first or last card

### ISSUE THREAD

**Issue by Shaomei** [aimpowered/ZoomCompanion#79]
Currently the left and right arrows are still clickable when reaching the first or last card. 
We should gray out (disable) the left arrow at the first card and gray out (disable) the right arrow at the last card.

See screenshots:
<img width="540" alt="Screenshot 2024-06-15 at 7 44 17 PM" src="https://github.com/aimpowered/ZoomCompanion/assets/202047/b5ad9c7e-314d-4831-a286-cc0793694ff8">
<img width="536" alt="Screenshot 2024-06-15 at 7 44 29 PM" src="https://github.com/aimpowered/ZoomCompanion/assets/202047/a36a7d84-9294-4142-86d3-b3781928e432">

**Comment by shubhankar-shandilya-india** [comment]
Hi @Shaomei 
You want the buttons to disappear or just fade on 1st and last page for left and right buttons respectively.

**Comment by Shaomei** [comment]
Hi @shubhankar-shandilya-india, I want the left arrow button to fade on 1st and the right arrow button to fade on the last page, just to indicate to the users that they have reach the beginning and/or the end of the carousal, respectively. 

Thanks for clarifying!

**Comment by Shaomei** [comment]
@ssunil3232, can you also move the arrows so that they are center on the circle?

**Comment by Shaomei** [comment]
This is fixed by PR #83 and #88. 

Close the issue now.
